;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.GreatSword.Attack1",DevComment="Character Ability - GreatSword combo 1")
+GameplayTagList=(Tag="Ability.GreatSword.Attack2",DevComment="")
+GameplayTagList=(Tag="Ability.GreatSword.Attack3",DevComment="")
+GameplayTagList=(Tag="Anim.Event.OnAttack",DevComment="")
+GameplayTagList=(Tag="Anim.Event.QueueNextCombo",DevComment="")
+GameplayTagList=(Tag="Anim.Event.RunNextCombo",DevComment="")
+GameplayTagList=(Tag="Data.DamageMultiplier",DevComment="")
+GameplayTagList=(Tag="Event.QueueNextCombo",DevComment="")
+GameplayTagList=(Tag="Event.RunNextCombo",DevComment="")

